// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omiemygbhddxezolndxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9taWVteWdiaGRkeGV6b2xuZHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjM0ODQsImV4cCI6MjA2OTczOTQ4NH0.XvMpm0o2ZjTWmTYjXIKI2VqwV4yQwiHV4n7mD3iJMKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});